import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

type PolicySection = {
  id: string;
  title: string;
  content: string[];
};

const policySections: PolicySection[] = [
  {
    id: "terms-of-service",
    title: "Terms of Service",
    content: [
      "MyAvatar - Terms of Service",
      "Effective Date: 20 April 2026",
      "Contact: studio@myavatar.co.za",
      "1. Scope and Acceptance",
      "These Terms of Service (\"Terms\") govern your access to and use of the MyAvatar platform, including our website, applications, and services.",
      "By accessing or using MyAvatar, you agree to be bound by these Terms, as well as our Privacy Policy, Refund Policy, and Acceptable Use Policy.",
      "2. Description of Services",
      "MyAvatar provides AI-powered tools that enable users to create digital avatars and generate video and audio content.",
      "3. Eligibility",
      "You must be at least 18 years old, or use the platform under the supervision of a parent or legal guardian.",
      "4. User Responsibilities",
      "You agree to:",
      "- Use the platform in compliance with all applicable laws",
      "- Ensure that you have the necessary rights and consent to use any content, likeness, or voice submitted",
      "- Comply with our Acceptable Use Policy",
      "You may not:",
      "- Impersonate any individual without consent",
      "- Create misleading, harmful, or unlawful content",
      "- Infringe intellectual property or privacy rights",
      "5. Content and Intellectual Property",
      "5.1 User Content",
      "You retain ownership of any content you upload or create using MyAvatar.",
      "5.2 License to MyAvatar",
      "You grant MyAvatar a limited, non-exclusive license to process, store, and use your content solely for the purpose of providing and improving the service.",
      "5.3 Responsibility",
      "You are solely responsible for all content generated, reviewed, and distributed through your use of the platform.",
      "6. AI-Generated Content Disclaimer",
      "Content generated by MyAvatar is produced using artificial intelligence and may not always be accurate, appropriate, or free from error.",
      "You are responsible for reviewing and approving all outputs before use.",
      "7. Payments and Billing",
      "- Certain features require payment or subscription",
      "- Pricing may change at any time",
      "- All payments are subject to our Refund Policy",
      "8. Account Management",
      "We reserve the right to suspend or terminate accounts that:",
      "- Violate these Terms or our Acceptable Use Policy",
      "- Engage in fraudulent, abusive, or unlawful activity",
      "9. Limitation of Liability",
      "To the maximum extent permitted by law, MyAvatar is provided \"as is\" without warranties of any kind.",
      "We are not liable for:",
      "- Indirect or consequential damages",
      "- Loss of data, revenue, or business opportunities",
      "- Misuse of generated content",
      "10. Changes to Terms",
      "We may update these Terms from time to time. Continued use of the platform constitutes acceptance of the updated Terms.",
      "11. Governing Law",
      "These Terms are governed by the laws of South Africa.",
      "12. Contact",
      "For any questions, contact: studio@myavatar.co.za",
    ],
  },
  {
    id: "privacy-policy",
    title: "Privacy Policy",
    content: [
      "MyAvatar - Privacy Policy",
      "Effective Date: 20 April 2026",
      "Contact: studio@myavatar.co.za",
      "1. Scope and Purpose",
      "This Privacy Policy applies to all users of the MyAvatar platform, including website visitors, registered users, and individuals who upload or interact with content.",
      "It explains how we collect, use, store, and protect personal information in accordance with the Protection of Personal Information Act (POPIA) and applicable data protection standards.",
      "2. Information We Collect",
      "2.1 Information You Provide",
      "- Name and contact details",
      "- Account and profile information",
      "- Uploaded content (images, videos, voice recordings)",
      "2.2 Automatically Collected Information",
      "- IP address",
      "- Device and browser information",
      "- Usage behaviour and interaction data",
      "3. Purpose of Processing",
      "We process personal information to:",
      "- Provide and operate the platform",
      "- Generate AI-based avatars and content",
      "- Process payments and manage accounts",
      "- Improve performance, security, and user experience",
      "- Comply with legal obligations",
      "4. Legal Basis",
      "Processing is based on:",
      "- Consent",
      "- Contractual necessity",
      "- Legitimate interests",
      "- Legal obligations",
      "5. Sharing of Information",
      "We may share data with:",
      "- Service providers (hosting, AI, payments)",
      "- Internal teams",
      "- Authorities where required by law",
      "We do not sell personal information.",
      "6. Cross-Border Transfers",
      "Data may be processed outside South Africa. Appropriate safeguards are implemented to ensure compliance with applicable laws.",
      "7. Security",
      "We implement reasonable technical and organisational measures, including secure infrastructure and access controls.",
      "8. Retention",
      "We retain data only as long as necessary for service delivery, legal compliance, and operational purposes.",
      "9. Children's Privacy",
      "The platform is not intended for children under 18 without consent.",
      "10. Marketing",
      "Users may opt in to receive communications and can unsubscribe at any time.",
      "11. Your Rights",
      "You may:",
      "- Access, correct, or delete your data",
      "- Withdraw consent",
      "- Object to processing",
      "12. Regulator",
      "Complaints may be directed to the Information Regulator of South Africa.",
      "13. Cookies",
      "We use cookies to improve functionality and analyse usage.",
      "14. Updates",
      "We may update this policy from time to time.",
      "15. Contact",
      "studio@myavatar.co.za",
    ],
  },
  {
    id: "refund-policy",
    title: "Refund Policy",
    content: [
      "MyAvatar - Refund Policy",
      "Effective Date: 20 April 2026",
      "Contact: studio@myavatar.co.za",
      "1. Scope",
      "This Refund Policy governs all purchases made on the MyAvatar platform and should be read alongside our Terms of Service.",
      "2. General Policy",
      "Due to the nature of digital and AI-generated services, all purchases are non-refundable.",
      "3. Eligible Refunds",
      "Refunds may be granted where:",
      "- A payment error has occurred",
      "- Technical issues prevented delivery of the service",
      "4. Non-Refundable Situations",
      "Refunds are not provided for:",
      "- Change of mind",
      "- Subjective dissatisfaction with output quality",
      "- Unused services or credits",
      "- Once a video, avatar, or AI generation process has started or costs have been incurred",
      "5. Refund Method",
      "Where a refund is approved, it will primarily be issued as platform credit to your MyAvatar account.",
      "- Credits can be used for future services on the platform",
      "- Processing fees or third-party costs may be deducted where applicable",
      "6. Refund Requests",
      "Requests must be submitted within 7 days of purchase to:",
      "studio@myavatar.co.za",
      "Please include:",
      "- Proof of payment",
      "- Description of the issue",
      "- Relevant account details",
      "7. Processing Time",
      "Approved refunds will be processed within 5-10 business days.",
      "8. Chargebacks",
      "Unauthorised chargebacks may result in account suspension and/or restriction of access to the platform.",
      "9. Updates",
      "We may update this policy from time to time. The latest version will always apply.",
    ],
  },
  {
    id: "acceptable-use-policy",
    title: "Acceptable Use",
    content: [
      "MyAvatar - Acceptable Use Policy",
      "Effective Date: 20 April 2026",
      "Contact: studio@myavatar.co.za",
      "1. Scope",
      "This policy forms part of the MyAvatar Terms of Service and applies to all users of the platform.",
      "2. Purpose",
      "MyAvatar must be used for lawful, ethical, and responsible purposes.",
      "3. Prohibited Uses",
      "3.1 Impersonation and Deception",
      "- Using another person's likeness without consent",
      "- Creating deceptive or fraudulent content",
      "- Producing harmful deepfakes",
      "3.2 Illegal or Harmful Content",
      "- Violating laws or regulations",
      "- Promoting harm, abuse, or discrimination",
      "3.3 Intellectual Property Violations",
      "- Using protected content without permission",
      "3.4 Privacy Violations",
      "- Misusing personal or sensitive information",
      "3.5 Platform Abuse",
      "- Hacking, reverse engineering, or system interference",
      "- Circumventing safeguards or controls",
      "4. User Responsibility",
      "You are responsible for:",
      "- Obtaining consent",
      "- Ensuring lawful use",
      "- Reviewing all generated content",
      "5. Enforcement",
      "We may:",
      "- Remove content",
      "- Suspend or terminate accounts",
      "- Report unlawful conduct",
      "6. Reporting",
      "Report violations to:",
      "studio@myavatar.co.za",
      "7. Updates",
      "We may update this policy from time to time.",
    ],
  },
];

const Policies = () => {
  const defaultPolicy = policySections[0]?.id ?? "";

  return (
    <div className="min-h-screen bg-background">
      <Header />

      <main className="pt-32 pb-24">
        <section className="container mx-auto px-6">
          <div className="max-w-4xl mx-auto">
            <p className="text-primary font-mono text-sm tracking-widest uppercase mb-3">
              Legal
            </p>
            <h1 className="font-display text-4xl md:text-5xl font-bold text-foreground mb-4">
              Policies and Procedures
            </h1>
            <p className="text-muted-foreground mb-10">
              Review all policy documents below. Use the tabs to navigate between each policy.
            </p>

            <Tabs defaultValue={defaultPolicy} className="w-full">
              <TabsList className="w-full h-auto grid grid-cols-2 md:grid-cols-4 gap-2 bg-muted/60 p-2">
                {policySections.map((policy) => (
                  <TabsTrigger key={policy.id} value={policy.id} className="w-full">
                    {policy.title}
                  </TabsTrigger>
                ))}
              </TabsList>

              {policySections.map((policy) => (
                <TabsContent
                  key={policy.id}
                  value={policy.id}
                  className="mt-6 glass-card p-6 md:p-8 space-y-4"
                >
                  <h2 className="font-display text-2xl font-semibold text-foreground">
                    {policy.title}
                  </h2>
                  {policy.content.map((paragraph) => (
                    <p key={paragraph} className="text-muted-foreground leading-relaxed whitespace-pre-wrap">
                      {paragraph}
                    </p>
                  ))}
                </TabsContent>
              ))}
            </Tabs>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default Policies;
